import { Conversation, ChatMessage } from './types';

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-1',
    auctionId: 101,
    productTitle: 'Organic Devgad Alphonso Mangoes (500 kg)',
    productImage: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=400&q=80',
    startingBid: 180,
    participantId: 15,
    participantName: 'Ramesh Patel (Farmer)',
    participantRole: 'FARMER',
    participantLocation: 'Ratnagiri, Maharashtra',
    lastMessage: 'I can offer ₹195/kg if you take the full 500 kg crate batch.',
    lastMessageTime: '10:42 AM',
    unreadCount: 2,
    status: 'ACTIVE',
  },
  {
    id: 'conv-2',
    auctionId: 102,
    productTitle: 'Grade-A Red Tomatoes (1000 kg)',
    productImage: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=400&q=80',
    startingBid: 28,
    participantId: 8,
    participantName: 'Suresh Kumar (Farmer)',
    participantRole: 'FARMER',
    participantLocation: 'Kolar, Karnataka',
    lastMessage: 'Deal agreed at ₹32/kg. Dispatching tomorrow morning.',
    lastMessageTime: 'Yesterday',
    unreadCount: 0,
    status: 'AGREED',
  },
  {
    id: 'conv-3',
    auctionId: 103,
    productTitle: 'Premium Sonam Rice (2000 kg)',
    productImage: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=400&q=80',
    startingBid: 55,
    participantId: 22,
    participantName: 'Apex Wholesale Traders',
    participantRole: 'BUYER',
    participantLocation: 'Bengaluru, Karnataka',
    lastMessage: 'Can you provide transport up to Electronic City hub?',
    lastMessageTime: '2 days ago',
    unreadCount: 0,
    status: 'ACTIVE',
  },
];

export const INITIAL_MESSAGES: Record<string, ChatMessage[]> = {
  'conv-1': [
    {
      id: 'm1',
      conversationId: 'conv-1',
      senderId: 10,
      senderName: 'You',
      senderRole: 'BUYER',
      text: 'Namaste Ramesh ji, I saw your listing for Devgad Alphonso Mangoes. Are these 100% naturally ripened without carbide?',
      timestamp: '10:30 AM',
      isRead: true,
    },
    {
      id: 'm2',
      conversationId: 'conv-1',
      senderId: 15,
      senderName: 'Ramesh Patel (Farmer)',
      senderRole: 'FARMER',
      text: 'Namaste ji! Yes, 100% organic, tree-ripened and grass-harvested from our orchard in Ratnagiri.',
      timestamp: '10:33 AM',
      isRead: true,
    },
    {
      id: 'm3',
      conversationId: 'conv-1',
      senderId: 10,
      senderName: 'You',
      senderRole: 'BUYER',
      text: 'Great! My bid is ₹185/kg for 300 kg. Can we close at this price?',
      timestamp: '10:35 AM',
      isRead: true,
      offer: {
        pricePerKg: 185,
        quantityKg: 300,
        totalAmount: 55500,
        status: 'PROPOSED',
      },
    },
    {
      id: 'm4',
      conversationId: 'conv-1',
      senderId: 15,
      senderName: 'Ramesh Patel (Farmer)',
      senderRole: 'FARMER',
      text: 'I can offer ₹195/kg if you take the full 500 kg crate batch.',
      timestamp: '10:42 AM',
      isRead: false,
      offer: {
        pricePerKg: 195,
        quantityKg: 500,
        totalAmount: 97500,
        status: 'COUNTERED',
      },
    },
  ],
  'conv-2': [
    {
      id: 'm201',
      conversationId: 'conv-2',
      senderId: 8,
      senderName: 'Suresh Kumar (Farmer)',
      senderRole: 'FARMER',
      text: 'Fresh harvest of Kolar Tomatoes ready for immediate loading.',
      timestamp: 'Yesterday 3:15 PM',
      isRead: true,
    },
    {
      id: 'm202',
      conversationId: 'conv-2',
      senderId: 10,
      senderName: 'You',
      senderRole: 'BUYER',
      text: 'Deal agreed at ₹32/kg. Dispatching tomorrow morning.',
      timestamp: 'Yesterday 4:00 PM',
      isRead: true,
      offer: {
        pricePerKg: 32,
        quantityKg: 1000,
        totalAmount: 32000,
        status: 'ACCEPTED',
      },
    },
  ],
  'conv-3': [
    {
      id: 'm301',
      conversationId: 'conv-3',
      senderId: 22,
      senderName: 'Apex Wholesale Traders',
      senderRole: 'BUYER',
      text: 'Can you provide transport up to Electronic City hub?',
      timestamp: '2 days ago',
      isRead: true,
    },
  ],
};
