import type { Metadata } from "next";
import {NextIntlClientProvider, useFormatter} from 'next-intl';
import "./globals.css";
import Header from "./ui/Header"
import Footer from "./ui/Footer"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col min-h-screen relative`}>
          <Header/>
          <NextIntlClientProvider>
        {children}
        </NextIntlClientProvider>
        <Footer/> 
      </body>
    </html>
  );
}