import type { Metadata } from "next";
import { NextIntlClientProvider } from 'next-intl';
import "./globals.css";
import { headers } from "next/headers";
import Header from "./ui/Header"
import Footer from "./ui/Footer"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerList = await headers();
  const pathname = headerList.get("x-current-path");
  function renderpaths() {
    if (pathname === '/auth/login' || pathname === '/auth/signup') {
      return (<> {children} </>)
    }
    else {
      return (<>
      <Header />
        <NextIntlClientProvider>
          {children}
        </NextIntlClientProvider>
        <Footer />
        </>);
    }
  }
  return (
    <html lang="en">
      <body
        className={`flex flex-col min-h-screen relative`}>
        {renderpaths()}
      </body>
    </html>
  );
}